### ISSUE TITLE
React-icons missing in kong plugin

### ISSUE THREAD

**Issue by dweber019** [veecode-platform/platform-backstage-plugins#14]
In https://github.com/veecode-platform/platform-backstage-plugins/blob/master/plugins/kong-service-manager/package.json the dependency https://www.npmjs.com/package/react-icons is missing, which is used at https://github.com/veecode-platform/platform-backstage-plugins/blob/master/plugins/kong-service-manager/src/components/RoutesList/ModalComponent/ModalComponent.tsx#L6

**Comment by luangazin** [comment]
Hi @dweber019,
Thank you for your report.
We have released a new version of the plugin with the fix.
https://www.npmjs.com/package/@veecode-platform/plugin-kong-service-manager/v/0.4.5

Let me know if you need any further adjustments!
