### ISSUE TITLE
 did anyone configured the gitlab pipeline plugin with the new backend api?

### ISSUE THREAD

**Issue by marabesi** [veecode-platform/platform-backstage-plugins#28]
A bit of context can be found here: https://github.com/veecode-platform/platform-backstage-plugins/issues/25

However I am wondering if the new backend API was used to configure the new plugin version? If so, can someone point to me where can I see a tutorial only for the new backend?

**Comment by rafaelgaldencio** [comment]
The only way I could make it work with Backstage 1.28 was by adding the following line to the proxy configuration
```diff
proxy:
  endpoints:
    '/gitlab/api':
      target: https://gitlab.com/api/v4
+     credentials: dangerously-allow-unauthenticated
      allowedHeaders: ['Authorization', 'Content-Type']
      headers:
        Accept: application/json 
        Content-Type: application/json
```

**Comment by marabesi** [comment]
well well well, that did the trick, thanks for that!

**Comment by marabesi** [comment]
adding the credentials to allow fixed my issue, however, is this the final solution?

**Comment by rafaelgaldencio** [comment]
I hope not. I'll try to do more debugging later to see if I can come up with the right solution, hopefully using `credentials: require`

**Comment by marabesi** [comment]
yep, I tried to understand the auth flow but at some point in time I got lost with the proxy, but I see that there is a exchange between the token we use and gitlab api. I will post any updates I might find in here as well.
